services:
  - type: web
    name: consumer-complaint-classification
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.runtime.txt
    startCommand: python app.py
    healthCheckPath: /
    autoDeploy: true
