"""Build the reproducible complaint-classification analysis notebook."""

from pathlib import Path

import nbformat as nbf


ROOT = Path(__file__).resolve().parents[1]
NOTEBOOK_PATH = ROOT / "notebooks" / "complaint_classification_report.ipynb"


def markdown(source: str):
    return nbf.v4.new_markdown_cell(source)


def code(source: str):
    return nbf.v4.new_code_cell(source)


def main() -> None:
    notebook = nbf.v4.new_notebook()
    notebook["metadata"] = {
        "kernelspec": {"display_name": "Complaint Classification (Python 3.11)", "language": "python", "name": "complaint-classification"},
        "language_info": {"name": "python", "version": "3.11"},
    }
    notebook["cells"] = [
        markdown("# Consumer Complaint Classification\n\n## tl;dr\n\n- The source file contained **162,421** rows; selecting the complaint narrative and product fields, removing blanks, and de-duplicating identical pairs produced **124,676** model-ready records.\n- The class distribution is imbalanced (4.179 largest-to-smallest ratio), so balanced class weighting is used in all trainable workflows.\n- On the full held-out test split, the deployed TF-IDF logistic-regression baseline achieved **0.8492 accuracy** and **0.8505 weighted F1**.\n- On a common 512-record held-out comparison sample, the baseline remains the selected deployment model (0.8374 weighted F1); GRU is the strongest recurrent model (0.8030). The one-epoch, 512-example CPU DistilBERT run is a workflow validation, not a competitive production fine-tune."),
        markdown("## Context & Methods\n\n### Key Assumptions\n\n- Input: `data/complaints_processed.csv`; prepared splits and reports are generated by `scripts/prepare_data.py`.\n- Splits are deterministic, stratified 70/15/15 using seed 42.\n- The full test split is used for the baseline and recurrent evidence. The all-model comparison uses a fixed 512-record test sample (seed 42) to keep CPU-bound DistilBERT evaluation bounded.\n- The selected model is chosen by weighted F1.\n\nThis notebook is a handoff artifact for analysts and reviewers, not the training implementation. Training commands are documented in `README.md`."),
        code("from pathlib import Path\nimport json\nimport pandas as pd\n\nROOT = Path.cwd()\nif not (ROOT / 'reports').exists():\n    ROOT = ROOT.parent\nassert (ROOT / 'reports').exists(), 'Run from the project root or notebooks directory.'\n\nwith (ROOT / 'reports' / 'data_summary.json').open(encoding='utf-8') as source:\n    data_summary = json.load(source)\nwith (ROOT / 'reports' / 'model_comparison.json').open(encoding='utf-8') as source:\n    comparison = json.load(source)\nwith (ROOT / 'artifacts' / 'deployment_model.json').open(encoding='utf-8') as source:\n    deployment = json.load(source)\n\nprint(f\"Selected model: {deployment['model_name']} ({deployment['selection_score']:.4f} weighted F1)\")"),
        markdown("## Data"),
        code("quality = pd.Series(data_summary['data_quality'], name='Value').to_frame()\nquality"),
        code("distribution = (pd.Series(data_summary['eda']['class_distribution'], name='Records')\n                .rename_axis('Product')\n                .reset_index())\ndistribution['Share'] = (distribution['Records'] / distribution['Records'].sum() * 100).round(1)\ndistribution"),
        code("pd.DataFrame([data_summary['eda']['complaint_length_words']])"),
        markdown("## Results"),
        code("model_results = (pd.DataFrame(comparison['models']).T\n                 .rename_axis('Model')\n                 .sort_values('f1_weighted', ascending=False))\nmodel_results"),
        code("top_words = pd.DataFrame(data_summary['eda']['top_30_words'], columns=['Word', 'Count'])\ntop_words.head(15)"),
        markdown("## Takeaways\n\n1. Keep the TF-IDF logistic-regression baseline in the Gradio app: it is the highest-scoring model in the current reproducible evidence and gives calibrated probability outputs for top-three routing suggestions.\n2. The GRU is the strongest custom recurrent candidate. It merits additional epochs and hyperparameter tuning if an all-neural deployment is required.\n3. DistilBERT should be retrained on the full prepared training split, preferably with GPU acceleration, before it is considered for selection. The present bounded run proves the Hugging Face pipeline and artifact flow only.\n4. Confidence must remain decision support, not an automatic routing decision. The UI presents both text and color status, ranked alternatives, and a local review history."),
    ]
    NOTEBOOK_PATH.parent.mkdir(parents=True, exist_ok=True)
    nbf.write(notebook, NOTEBOOK_PATH)
    print(NOTEBOOK_PATH)


if __name__ == "__main__":
    main()
